export const invoiceList = [
    {
        ID: 1,
        INVOICE_NUMBER: 1001,
        ORDER_ID: "ORD-1001",
        INVOICE_DATE: "2025-04-01T10:00:00.000Z",
        INVOICE_TYPE_CODE: "STANDARD",
        NET_AMOUNT: 1200,
        INVOICE_TVA: 0.19,
        AMOUNT_TVA: 228,
        AMOUNT_TTC: 1428,
        INVOICE_STATE_CODE: "PAID",
        ORDER_NAME: "Website Development",
        CLIENT_CODE: 501,
        CLIENT_NAME: "Acme Corp",
        CLIENT_NRC: "RC123456789",
        CLIENT_ADDRESS: "123 Business St, Paris, France",
        CLIENT_MAIL: "contact@acme.com",
        CLIENT_IDF: "FR123456789",
        PRODUCT_NAME: "Web App",
        IS_PAID: true
    },
    {
        ID: 2,
        INVOICE_NUMBER: 1002,
        ORDER_ID: "ORD-1002",
        INVOICE_DATE: "2025-04-03T15:30:00.000Z",
        INVOICE_TYPE_CODE: "STANDARD",
        NET_AMOUNT: 1500,
        INVOICE_TVA: 0.19,
        AMOUNT_TVA: 285,
        AMOUNT_TTC: 1785,
        INVOICE_STATE_CODE: "PAID",
        ORDER_NAME: "Mobile App Design",
        CLIENT_CODE: 502,
        CLIENT_NAME: "Beta Ltd",
        CLIENT_NRC: "RC987654321",
        CLIENT_ADDRESS: "45 Innovation Ave, Lyon, France",
        CLIENT_MAIL: "info@beta.com",
        CLIENT_IDF: "FR987654321",
        PRODUCT_NAME: "Design Mockups",
        IS_PAID: true
    },
    {
        ID: 3,
        INVOICE_NUMBER: 1003,
        ORDER_ID: "ORD-1003",
        INVOICE_DATE: "2025-04-05T09:15:00.000Z",
        INVOICE_TYPE_CODE: "PROFORMA",
        NET_AMOUNT: 1000,
        INVOICE_TVA: 0.19,
        AMOUNT_TVA: 190,
        AMOUNT_TTC: 1190,
        INVOICE_STATE_CODE: "UNPAID",
        ORDER_NAME: "API Development",
        CLIENT_CODE: 503,
        CLIENT_NAME: "Gamma Solutions",
        CLIENT_NRC: "RC456123789",
        CLIENT_ADDRESS: "78 Digital Blvd, Marseille, France",
        CLIENT_MAIL: "dev@gammasolutions.fr",
        CLIENT_IDF: "FR456123789",
        PRODUCT_NAME: "REST API",
        IS_PAID: false
    },
    {
        ID: 4,
        INVOICE_NUMBER: 1004,
        ORDER_ID: "ORD-1004",
        INVOICE_DATE: "2025-04-06T11:45:00.000Z",
        INVOICE_TYPE_CODE: "STANDARD",
        NET_AMOUNT: 500,
        INVOICE_TVA: 0.2,
        AMOUNT_TVA: 100,
        AMOUNT_TTC: 600,
        INVOICE_STATE_CODE: "UNPAID",
        ORDER_NAME: "Hosting Package",
        CLIENT_CODE: 504,
        CLIENT_NAME: "Delta Hosting",
        CLIENT_NRC: "RC753951456",
        CLIENT_ADDRESS: "9 Server Rd, Lille, France",
        CLIENT_MAIL: "billing@deltahosting.com",
        CLIENT_IDF: "FR753951456",
        PRODUCT_NAME: "Web Hosting",
        IS_PAID: false
    }
];

export const invoice =
    {
        ID: 1,
        INVOICE_NUMBER: 1001,
        ORDER_ID: "ORD-1001",
        INVOICE_DATE: "2025-04-01T10:00:00.000Z",
        INVOICE_TYPE_CODE: "STANDARD",
        NET_AMOUNT: 1200,
        INVOICE_TVA: 0.19,
        AMOUNT_TVA: 228,
        AMOUNT_TTC: 1428,
        INVOICE_STATE_CODE: "PAID",
        ORDER_NAME: "Website Development",
        CLIENT_CODE: 501,
        CLIENT_NAME: "Acme Corp",
        CLIENT_NRC: "RC123456789",
        CLIENT_ADDRESS: "123 Business St, Paris, France",
        CLIENT_MAIL: "contact@acme.com",
        CLIENT_IDF: "FR123456789",
        PRODUCT_NAME: "Web App",
        IS_PAID: true
    }

