export const payementList= [
    {
      ID: 1,
      DATE: "2025-04-10T15:26:18.913Z",
      ACTION_CODE_DESCRIPTION: "Transaction refusée : solde insuffisant. Code erreur : 100",
      ACTION_CODE: 100,
      AMOUNT: 1500,
      AUTH_CODE: 987654,
      CURRENCY: "012", // Dinar algérien
      ERROR_CODE: "3",
      ERROR_MESSAGE: "Échec de la confirmation de commande",
      CARD_HOLDER_NAME: "K. AMINE",
      EXPIRATION: "202701",
      ORDER_NUMBER: "ORD-1001",
      SATIM_ORDER_ID: "ABC123XYZ",
      ORDER_STATUS: 0,
      APPROVAL_CODE: null,
      RETURNED_CODE: null,
      RESPONSE_CODE_DESCRIPTION: "Transaction refusée : carte expirée",
      RESPONSE_CODE: "62",
      UDF1: "UDFVAL1",
      UDF2: null,
      UDF3: null,
      UDF4: null,
      UDF5: null,
      REGISTER_ID: null,
      REGISTER: null
    },
    {
      ID: 2,
      DATE: "2025-04-12T09:15:00.000Z",
      ACTION_CODE_DESCRIPTION: "Transaction approuvée",
      ACTION_CODE: 0,
      AMOUNT: 3500,
      AUTH_CODE: 123456,
      CURRENCY: "012",
      ERROR_CODE: "0",
      ERROR_MESSAGE: "",
      CARD_HOLDER_NAME: "L. NADIA",
      EXPIRATION: "202512",
      ORDER_NUMBER: "ORD-1002",
      SATIM_ORDER_ID: "XYZ456DEF",
      ORDER_STATUS: 1,
      APPROVAL_CODE: "APPROVED123",
      RETURNED_CODE: "00",
      RESPONSE_CODE_DESCRIPTION: "Transaction réussie",
      RESPONSE_CODE: "00",
      UDF1: "2018105301346",
      UDF2: "Extra info",
      UDF3: null,
      UDF4: null,
      UDF5: null,
      REGISTER_ID: "REG001",
      REGISTER: "Web"
    },
    {
      ID: 3,
      DATE: "2025-04-15T13:30:45.123Z",
      ACTION_CODE_DESCRIPTION: "Transaction annulée par l’utilisateur",
      ACTION_CODE: 200,
      AMOUNT: 10000,
      AUTH_CODE: 654321,
      CURRENCY: "012",
      ERROR_CODE: "2",
      ERROR_MESSAGE: "Annulation par le client",
      CARD_HOLDER_NAME: "M. YASSINE",
      EXPIRATION: "202611",
      ORDER_NUMBER: "ORD-1003",
      SATIM_ORDER_ID: "LMN789GHI",
      ORDER_STATUS: 9,
      APPROVAL_CODE: null,
      RETURNED_CODE: null,
      RESPONSE_CODE_DESCRIPTION: null,
      RESPONSE_CODE: null,
      UDF1: null,
      UDF2: null,
      UDF3: null,
      UDF4: null,
      UDF5: null,
      REGISTER_ID: null,
      REGISTER: "Mobile"
    }
  ];

  export const payement ={
    ID: 1,
    DATE: "2025-04-10T15:26:18.913Z",
    ACTION_CODE_DESCRIPTION: "Transaction refusée : solde insuffisant. Code erreur : 100",
    ACTION_CODE: 100,
    AMOUNT: 1500,
    AUTH_CODE: 987654,
    CURRENCY: "012", // Dinar algérien
    ERROR_CODE: "3",
    ERROR_MESSAGE: "Échec de la confirmation de commande",
    CARD_HOLDER_NAME: "K. AMINE",
    EXPIRATION: "202701",
    ORDER_NUMBER: "ORD-1001",
    SATIM_ORDER_ID: "ABC123XYZ",
    ORDER_STATUS: 0,
    APPROVAL_CODE: null,
    RETURNED_CODE: null,
    RESPONSE_CODE_DESCRIPTION: "Transaction refusée : carte expirée",
    RESPONSE_CODE: "62",
    UDF1: "UDFVAL1",
    UDF2: null,
    UDF3: null,
    UDF4: null,
    UDF5: null,
    REGISTER_ID: null,
    REGISTER: null
  }
  

